
// login user
export const API_REQUEST_LOGIN = 'API_REQUEST_LOGIN';
export const API_REQUEST_SUCCEEDED_LOGIN = 'API_REQUEST_SUCCEEDED_LOGIN';
export const API_REQUEST_FAILED_LOGIN = 'API_REQUEST_FAILED_LOGIN';

